### ISSUE TITLE
Initial user's presence status deprecated in Slack RTM Api

### ISSUE THREAD

**Issue by csoni111** [captn3m0/slack-utils#5]
As per [https://api.slack.com/docs/presence-and-status#batching](https://api.slack.com/docs/presence-and-status#batching)

`presence_change event behavior will change on November 15, 2017. Subscriptions will become mandatory.`

Slack no more sends initial presence status for users (it shows all users as `away`) and no further `presence_change` events are sent in RTM Api.

**Comment by csoni111** [comment]
More detail here https://api.slack.com/events/presence_change

**Comment by captn3m0** [comment]
@csoni111 Added you as collaborator on the repo. Just make sure that all code is covered with tests.

**Comment by csoni111** [comment]
@captn3m0 can you please update the version 0.3.2 on npm?

**Comment by captn3m0** [comment]
Published 👍
